spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/darknerdquizappquizdb
    username: postgres
    password: 10702

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true


logging:
  level:
    com:
      darknerd:
        quizapp: DEBUG


server:
  port: 8083
  servlet:
    context-path: /dark-nerd-quiz-app-quiz-service