spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/quizappquestionsdb
    username: postgres
    password: 10702

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true


  sql:
    init:
#      data-locations: classpath:question-table-data.sql


logging:
  level:
    com:
      darknerd:
        quizapp: DEBUG


server:
  servlet:
    context-path: /darknerd-quizapp