spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/darknerdquizappquestiondb
    username: postgres
    password: 10702

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true


logging:
  level:
    com:
      darknerd:
        quiz_app_question_service: DEBUG


server:
  servlet:
    context-path: /dark-nerd-quiz-app-question-service